### ISSUE TITLE
When a marker is overlapping another, the Resize grips behind it are not accessible

### ISSUE THREAD

**Issue by tarngerine** [ailon/markerjs2#125]
Repro:
1. Draw two rectangles, overlapping each other
2. Select the first one (the one that's "behind")
3. Try to resize the corner that's intersecting the second rect
4. You cannot reach it because of the way the DOM is set up

I'm not sure there's a straight forward solution here but just wanted to flag it. In a previous project where I built an SVG-based interface like this, I created a group for just the resize handles that was always at the "top" of the DOM within SVG, and sent the current size and rotation data over there, like:

```
<svg>
  <g>
    // every element
    <rect>
    <circle>
    <text>
  </g>
  <g>
    // resize handles go here
    <circle>
    <circle>
    <circle>
    <circle>
  </g>
</svg>
```

**Comment by ailon** [comment]
Well, this is not a "bug" it's a "feature" :) Seriously, though, it's just how it is "by design". 

Your proposed solution would work but would be a breaking change across the board. I think a more realistic workaround would be to pop the selected marker on top of the stack on select and then push it back to its level on deselect. I'll think about this for some time and, if I can't think of reasons not to do it, implement this in a future update.

**Comment by tarngerine** [comment]
Oh yea that's way smarter of a method!
