### ISSUE TITLE
How can I set marker's default width and height?

### ISSUE THREAD

**Issue by jisujisubaek** [ailon/markerjs2#145]
Hello!
I want to set marker's default width and height.
not drag. When I click to create rect or other marker.
How can I set marker's default width and height?

Your library is awesome! I'm getting a lot of help. Thank you.

**Comment by ailon** [comment]
Hey there!

The short "official" answer - you can't.

The longer answer is that there are several "hacky options" that come to mind:

1) you can fork the code and recompile with different defaults
2) you can react to `markercreating` event and set it there. Something like this should work:

```
  markerArea.addEventListener(
    "markercreating",
    (event) => (event.marker.defaultSize = { x: 10, y: 100 })
  );
```

The problem here is that `defaultSize` is `protected` in TypeScript, so conceptually you can't access it. Except it's all JavaScript and in fact you can :)

**Comment by jisujisubaek** [comment]
It works perfectly! Thank you very much. Have a nice day :)
