### ISSUE TITLE
Add correct cursors to markers

### ISSUE THREAD

**Issue by bennymeier** [ailon/markerjs2#160]
Hi,

is it possible to add the correct cursors to the marker points where I can resize or move the markers?
On the corners I would expect the nw-resize and ne-resize cursors. And in the middle left and middle right the w-resize cursor. On top middle and down middle the s-resize cursor.

Currently there is always the move cursor which sometimes confuses me.
![Cursors](https://i.imgur.com/GGXTt9D.jpg)

Many greetings
Benny

**Comment by ailon** [comment]
Yeah, I've made an attempt to address this a few times (starting before the v2 release, probably it even worked like that in v1). BUT, you forget that markers can be rotated in v2 and that's where this breaks. Couldn't figure out a way to make it look not weird at some angles. 

Unless a way to rotate cursors was introduced since I last looked just having it as a "neutral" `move` cursor is the least confusing option, imho.
