### ISSUE TITLE
Popup position moves after keyboard opens/closes on mobile

### ISSUE THREAD

**Issue by ahaurat** [ailon/markerjs2#170]
To reproduce:
- Visit the popup sandbox on mobile (iPhone in my case): https://codesandbox.io/s/9707i
- Use the text tool to add text
- Close the keyboard and the popup position is now too high (see screenshot) and the tools are no longer accessible

![IMG_3785](https://github.com/ailon/markerjs2/assets/3485980/dfcb6e74-956d-4d02-9ed2-7edaf54260e2)

**Comment by ailon** [comment]
I can see the page shifting a bit on an iPhone (not on Android though). Not to the point of toolbar getting off-screen, but yeah I can see how this can become problematic. I remember fighting Safari on a text input related issue a while back but can't recall the details. Will need to investigate.

Do you experience the same issue in your own implementation or just on codesandbox? Just asking because it could be a little "special case" over there.

**Comment by ahaurat** [comment]
I see it in my own implementation as well; I only used the codesandbox link since it's an easy way to reproduce. Thanks for taking a look!

**Comment by ailon** [comment]
I've changed how the popup is positioned and it seems to have fixed it in my local tests and in the [demo on markerjs.com](https://codesandbox.io/s/9707i) still acts weird in the codesandbox demo, but the whole codesandbox UI seems to get shifted/extended, so maybe that's not a marker.js issue there.

Let me know if 2.31.2 fixes it for your case.
