### ISSUE TITLE
Add custom ui elements to popup marker area

### ISSUE THREAD

**Issue by sid-pwh** [ailon/markerjs2#171]
It will be great to have a configuration, ui settings, where we can add custom ui element in one particular location in the markup area. For me the use case is, I want to add legends for different color codes for frame marker. This will help me annotating the text in my image properly with the provided legends. So do you think we can do something about this?

**Comment by ailon** [comment]
Do you mean it as a guide for the user? Like "red" means bad and "green" means good?

I don't think I see a universal way or wide-enough demand for something like this.

Having said that, I see at least two workarounds to achieve this:

1) When creating a new marker area, you can populate it with markers representing your legend (rectangles + text markers) and users can then delete it when done. Or you can set some "tags" in the `notes` field so you can remove them programmatically on save.
2) Instead of using marker.js' `popup` mode you can create your own popup with the legend and then use marker.js in `inline` mode inside of it.

Hope this helps.

**Comment by socialmedialabs** [comment]
Currently we're evaluating markerjs2 and came accross a scenario where we'd like to add custom buttons with custom actions, i. e. we'd like to add copy, paste and duplicate buttons. Being able to add custom buttons to the toolbar and the toolbox seems kinda essential to me.
I see other possible use cases as well, e. g. when you want to add a help button that shows usage instructions for the not so tech savvy ones, etc.

**Comment by socialmedialabs** [comment]
> @socialmedialabs not sure what this has to do with this specific issue.

I didn't mean to pollute your issues section, hence posting here as I thought this would go into the same direction.
Thank you for your answer, I'll open a new issue.
