### ISSUE TITLE
Help with render addEventListener

### ISSUE THREAD

**Issue by waruhachi** [ailon/markerjs2#186]
Hello,

I'm trying to use the library but the code inside the render event never runs. My end goal is to do some processing on the edited image. I have to do this to bypass the Tainted canvases issue because the anonymous cross-origin solution cannot be used in my situation.

Please guide me in the correct direction.

```js
function showMarkerArea(target) {
    var markerArea = new markerjs2.MarkerArea(target);

    markerArea.settings.displayMode = 'popup';

    markerArea.addEventListener("render", (event) => {
      console.log(event);
      target.src = event.dataUrl;
    });

    markerArea.show();
  }
  ```

**Comment by ailon** [comment]
Hi. Based on the intro paragraph, I assume that the code in the render event handler doesn't run simply because you get a CORS/tainted canvas error before it could run, correct? 

If the CORS issue cannot be resolved in an orderly fashion, then I think the only option is to look for some tricks to work around it. I think quite a while ago I saw some libraries that would somehow download and regenerate the images, or something like that. Unfortunately, I don't have any links or specific details handy. But hopefully this gives you some hints on what to look for.

**Comment by waruhachi** [comment]
Hey,

Thanks for the response! I was able to solve the tainted canvas issue.
