### ISSUE TITLE
How to release focus on the current marker? 

### ISSUE THREAD

**Issue by kchagam** [ailon/markerjs2#36]
After annotating with some shape,  The final annotated image needs to be saved with some label, so i want to allow the user to enter name while annotating, but when user moves to text input and starts typing the last Drawing shape is getting removed.

**Note**: there is not a problem if User clicks out of the shape after using Marker type , it's happening only last drawing shape was in focus.

is there any way to release focus?

**Comment by ailon** [comment]
Interesting. I will look into why this happens and try to fix it. In the meantime, is rendering the marked image before the user enters that text not an option? You can initiate rendering from code via [MarkerArea.startRenderAndClose()](https://markerjs.com/reference/classes/markerarea.html#startrenderandclose)

Otherwise, there's a `MarkerArea.setCurrentMarker()` method which when called without a parameter will deselect currently selected marker. But it's marked as `private` in TypeScript right now. I plan to make it public in the next release but if for now if you are using TS you'll have to work around it.

**Comment by kchagam** [comment]
thank for the reply.  

>  In the meantime, is rendering the marked image before the user enters that text not an option? You can initiate rendering from code via MarkerArea.startRenderAndClose()

no, i would like to let the user modify added annotations before saving the final one, so this is not an option. 

thank for this suggestion  `MarkerArea.setCurrentMarker()` ,  it's working 

thank you @ailon  for this amazing tool.
