### ISSUE TITLE
Angular Implementation

### ISSUE THREAD

**Issue by JuergsPona** [ailon/markerjs2#4]
Hey, thanks for this awesome product.

I've been trying to implement the code using the node package as per the documentation, and I am running into the following issue:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/12148895/107343043-a094a900-6ac9-11eb-8c88-93cda87288f9.png">

**Node version: v12.18.2
NPM version: 6.14.5
markerjs2 version: 2.3.2 (latest)**

I've attempted to test a few versions going back to v2.0.0.

Please advise if there's anything I could be doing incorrectly, or if there is something I need to do specific to Angular.

**Comment by ailon** [comment]
Hi there. 

It's hard to say what's wrong from just the error message. I don't have experience with Angular in particular but I suspect this is not related to Angular in particular but rather to the implementation details.

If you could create a simple repro on codesandbox or something similar I could take a look. Otherwise, it's hard to advise anything without seeing code.

Alan.

**Comment by JuergsPona** [comment]
Hey Alan, thanks for the quick reply.

Here's the live link (not entirely sure how code sandbox works)
https://codesandbox.io/live/l4w0tjg

I'm not getting the error in the sandbox, but I believe that's because I'm not implementing the code correctly. The code does mimic what I have at the moment.

Regards,
Juergen

**Comment by ailon** [comment]
Replace:

```js
this.marker = new markerjs2.MarkerArea(this.markerImg);
```
with
```js
this.marker = new markerjs2.MarkerArea(this.markerElement);
```

and it seems to work fine then.

**Comment by JuergsPona** [comment]
Ah! That's the solution! Thanks so much, I had a feeling it would boil down to a simple change 😅

Thanks once again for the awesome component!
