### ISSUE TITLE
Image is distored on popup mode with "renderAtNaturalSize" enabled and image bigger than parent

### ISSUE THREAD

**Issue by Reykugo-Gear** [ailon/markerjs2#44]
actual result : 
![image](https://user-images.githubusercontent.com/67274660/122539541-010f9600-d028-11eb-85fa-92b046b3f2c2.png)

expected result : 
![image](https://user-images.githubusercontent.com/67274660/122539652-1c7aa100-d028-11eb-967a-ae60da869cb8.png)

my current hotfix: 
![image](https://user-images.githubusercontent.com/67274660/122539719-2ef4da80-d028-11eb-84ca-e2591f0dac89.png)

**Comment by ailon** [comment]
Hi. On the first glance, it looks like the image has some orientation properties that is handled properly somewhere but then displayed ignoring the orientation in the image. Would it be possible for you to share that exact image so I can investigate?

Also, what browser and OS is this? Is marker.js in popup mode?

**Comment by Reykugo-Gear** [comment]
> Hi. On the first glance, it looks like the image has some orientation properties that is handled properly somewhere but then displayed ignoring the orientation in the image. Would it be possible for you to share that exact image so I can investigate?
> 
> Also, what browser and OS is this? Is marker.js in popup mode?

The image has the good orientation (i just take random image). But i have the same result with other big images.
Yes marker.js is on mode popup. My os is Windows 10 (v 20H2)

original image
![Snapchat-881652440 0717](https://user-images.githubusercontent.com/67274660/122543641-4635c700-d02c-11eb-81f1-5cddde1438d9.png)

another image that has same issue:
![cat](https://user-images.githubusercontent.com/67274660/122543804-7715fc00-d02c-11eb-9fd9-4b316ec6d1f3.jpg)

example bad rendering with other image : 
![image](https://user-images.githubusercontent.com/67274660/122544096-bd6b5b00-d02c-11eb-893e-ffe763275354.png)

**Comment by ailon** [comment]
OK, I'll look into it.

Btw, `renderAtNaturalSize` has nothing to do with how the image is displayed in marker.js. It's a setting for how the result is rendered when user presses "OK" (or the method is called from code).

**Comment by ailon** [comment]
Hmm... Can't reproduce this issue with your image (or any other image). Could it be that something on your page affects this? (eg. some global style set on img elements or something?)

Also, would it be possible for you to create a repro on codesandbox or somewhere?

**Comment by Reykugo-Gear** [comment]
> Hmm... Can't reproduce this issue with your image (or any other image). Could it be that something on your page affects this? (eg. some global style set on img elements or something?)
> 
> Also, would it be possible for you to create a repro on codesandbox or somewhere?

Ok i can't reproduce the exact same issue but i've also bad rendering with this https://codesandbox.io/s/silly-swartz-jn3ly?file=/src/index.js

Origin image at position absolute seems to be problematic. i've copy all css properties image of my business isssues in this sandbox

**Comment by Reykugo-Gear** [comment]
Note: my hotfix doesn't work because it broke markers position in image

**Comment by ailon** [comment]
Sorry it took this long to get to this. I've investigated this now and, to be honest, I don't know how to proceed. Or if this should be addressed on the marker.js side at all.

The problem seems to be that you style image heavily and marker.js uses the dimensions of the image object (namely clientWidth and clientHeight) to determine the size of the image to be edited. However, the image itself is modified in multiple ways in your CSS. Particularly, `object-fit: contain;` results in image being displayed correctly visually, while the dimensions of the image object stay skewed and that causes the distortion in the marker.js editing view.

![image](https://user-images.githubusercontent.com/179076/125252724-5b3b0880-e301-11eb-9b60-5c6cf3521879.png)

Here you can see that the img element (dimensions used by marker.js) is wider than the visible image.

I don't claim to be a CSS expert, but I personally would wrap an image in some container and apply all of these manipulations on a wrapper rather than on the image itself.

So that's where I'm stuck now. If anyone has any ideas on how to get the **visible** dimensions of that image rather than image object, I'm happy to take a swing on this issue. I could probably use natural image size instead of clientWidth/Height but that isn't necessarily what other users may want (the image could be skewed on purpose).

But I'm leaning to recommending that you avoid styling the img element like this and focus on the wrapper instead.

**Comment by etiennebeaulac** [comment]
Hi!

I encountered this problem with a lot less of custom CSS. As @ailon mentionned, the culprit seems to be `object-fit: contain`. As suggested, I tried to wrap the `img` in a container div, but I was not able to replicate that behavior I wanted without `object-fit`.

Here is the solution I ended up with, if it can help anyone. I duplicate the image in a "dummy" element that can then be edited by markerjs :

```
const img = document.getElementById("myImage");
const dummy = document.createElement("img");
dummy.src = img.src;
dummy.style.visibility = "hidden";
document.body.appendChild(dummy);

const marker = new markerjs2.MarkerArea(dummy);
marker.settings.displayMode = "popup";

marker.addEventListener("render", (event) => {
  img.src = event.dataUrl;
});

marker.addEventListener("close", (event) => {
  document.body.removeChild(dummy);
})

marker.show();
```
