### ISSUE TITLE
Would it be possible to save freehand drawings as an array of x/y points or some other way, instead of as an image?

### ISSUE THREAD

**Issue by Dima-369** [ailon/markerjs2#84]
I see that other markers are stored via keys like `top, left, width, height, x, y`, etc., but I would find it very interesting for submitting to a JSON API if freehand drawings would also be stored that way.

Right now, freehand drawings are stored as an image which is not editable.
  
Is it possible to implement this in the current code base without major changes?

**Comment by ailon** [comment]
Unlike all other markers, Freehand is a raster image (based on canvas) rather than SVG vector object (like every other marker). So there's no way to edit it. Technically, it would be possible to implement a version of freehand marker as an SVG polyline or something like that. Having said that, "editing" it would be quite out of scope for what marker.js is. Sure, it would be possible to change the color post-factum, but I'm not sure it's a worthwhile endeavor for a rewrite. Also, it could get really slow if a user does a lot of freehand drawing this way.

Also, there's no "JSON API" per se :) That's just a serialization of the internal marker.js state which is undocumented and shouldn't be modified directly.
