### ISSUE TITLE
Typing text in a TextMarker and submitting it changes the marker size initially?

### ISSUE THREAD

**Issue by Dima-369** [ailon/markerjs2#87]
This seems like a bug to me on Firefox? Here is a video to demonstrate the behavior:

I would expect the marker to stay the size when tying in the text.

https://user-images.githubusercontent.com/15002298/168656170-e22a5e21-c400-4748-bdb9-5174979e72a1.mov

**Comment by ailon** [comment]
Looks to me that it stays the same size as you have drawn with the mouse which is the expected behavior (by-design) and not specific to Firefox. It tries to fit the text into the same marker "box". So if you type more text the font gets smaller and if you type less text the font gets bigger. Or am I missing something here?

**Comment by Dima-369** [comment]
Oh, now I 'get' the behavior.!Yeah, it correctly fits the text into the initially dragged area and adjusts the text size.

Sorry for the hiccup, this works as expected!
